---

- name: database schema is uploaded
  template:
    src: "schema.sql.j2"
    dest: "{{ seed_remote_temp_dir }}/schema.sql"
  register: _seed_schema_uploaded

- name: database schema is spplied
  shell: mysql -h "{{ _seed_mysql.host }}"
          --user="{{ _seed_mysql.user }}"
          --password={{ _seed_mysql.password }}
          < "{{ seed_remote_temp_dir }}/schema.sql"
